DROP VIEW visitor_summary_all_v;
DROP VIEW visitor_summary_v;

DROP VIEW player_v;

DROP MATERIALIZED VIEW player_surface_goat_points;
DROP VIEW player_surface_goat_points_v;
DROP VIEW player_surface_best_season_goat_points_v;
DROP VIEW player_surface_big_wins_goat_points_v;
DROP VIEW player_surface_best_rank_goat_points_v;
DROP MATERIALIZED VIEW player_surface_season_goat_points;
DROP VIEW player_surface_season_goat_points_v;
DROP MATERIALIZED VIEW player_goat_points;
DROP VIEW player_goat_points_v;
DROP VIEW player_best_season_goat_points_v;
DROP VIEW player_best_season_v;
DROP VIEW player_big_wins_goat_points_v;
DROP MATERIALIZED VIEW player_season_goat_points;
DROP VIEW player_season_goat_points_v;

DROP VIEW player_best_elo_rating_goat_points_v;
DROP VIEW player_best_surface_elo_rating_goat_points_v;
DROP VIEW player_weeks_at_elo_topn_goat_points_v;
DROP VIEW player_season_weeks_at_elo_topn_goat_points_v;
DROP VIEW player_weeks_at_surface_elo_topn_goat_points_v;
DROP VIEW player_season_weeks_at_surface_elo_topn_goat_points_v;
DROP VIEW player_weeks_at_no1_goat_points_v;
DROP VIEW player_season_weeks_at_no1_goat_points_v;
DROP VIEW player_season_big_wins_goat_points_v;
DROP VIEW player_surface_season_big_wins_goat_points_v;
DROP VIEW player_surface_h2h_goat_points_v;
DROP VIEW player_career_grand_slam_goat_points_v;
DROP VIEW player_season_grand_slam_goat_points_v;
DROP VIEW player_grand_slam_holder_goat_points_v;
DROP VIEW player_consecutive_grand_slam_on_same_event_goat_points_v;
DROP VIEW player_grand_slam_on_same_event_goat_points_v;
DROP VIEW player_greatest_rivalries_goat_points_v;
DROP VIEW player_surface_greatest_rivalries_goat_points_v;
DROP VIEW player_records_goat_points_v;
DROP VIEW player_surface_records_goat_points_v;
DROP VIEW player_performance_goat_points_v;
DROP VIEW player_statistics_goat_points_v;

DROP MATERIALIZED VIEW player_h2h;
DROP VIEW player_h2h_v;
DROP MATERIALIZED VIEW title_difficulty;
DROP VIEW title_difficulty_v;

DROP MATERIALIZED VIEW player_weeks_at_elo_topn;
DROP VIEW player_weeks_at_elo_topn_v;
DROP MATERIALIZED VIEW player_season_weeks_at_elo_topn;
DROP VIEW player_season_weeks_at_elo_topn_v;
DROP VIEW topn_player_elo_ranking_v;
DROP MATERIALIZED VIEW player_weeks_at_surface_elo_topn;
DROP VIEW player_weeks_at_surface_elo_topn_v;
DROP MATERIALIZED VIEW player_season_weeks_at_surface_elo_topn;
DROP VIEW player_season_weeks_at_surface_elo_topn_v;
DROP VIEW topn_player_surface_elo_ranking_v;
DROP MATERIALIZED VIEW player_weeks_at_no1;
DROP VIEW player_weeks_at_no1_v;
DROP MATERIALIZED VIEW player_season_weeks_at_no1;
DROP VIEW player_season_weeks_at_no1_v;
DROP VIEW no1_player_ranking_v;

DROP MATERIALIZED VIEW player_current_rank;
DROP VIEW player_current_rank_v;
DROP MATERIALIZED VIEW player_best_rank;
DROP VIEW player_best_rank_v;
DROP MATERIALIZED VIEW player_best_rank_points;
DROP VIEW player_best_rank_points_v;
DROP MATERIALIZED VIEW player_year_end_rank;
DROP VIEW player_year_end_rank_v;
DROP MATERIALIZED VIEW player_current_elo_rank;
DROP VIEW player_current_elo_rank_v;
DROP MATERIALIZED VIEW player_best_elo_rank;
DROP VIEW player_best_elo_rank_v;
DROP MATERIALIZED VIEW player_best_elo_rating;
DROP VIEW player_best_elo_rating_v;
DROP MATERIALIZED VIEW player_season_best_elo_rating;
DROP VIEW player_season_best_elo_rating_v;
DROP MATERIALIZED VIEW player_year_end_elo_rank;
DROP VIEW player_year_end_elo_rank_v;

DROP MATERIALIZED VIEW player_performance;
DROP VIEW player_performance_v;
DROP MATERIALIZED VIEW player_season_performance;
DROP VIEW player_season_performance_v;
DROP MATERIALIZED VIEW player_tournament_performance;
DROP VIEW player_tournament_performance_v;
DROP MATERIALIZED VIEW player_stats;
DROP VIEW player_stats_v;
DROP MATERIALIZED VIEW player_season_stats;
DROP VIEW player_season_stats_v;
DROP MATERIALIZED VIEW player_surface_stats;
DROP VIEW player_surface_stats_v;
DROP MATERIALIZED VIEW player_season_surface_stats;
DROP VIEW player_season_surface_stats_v;

DROP MATERIALIZED VIEW player_win_streak;
DROP VIEW player_win_streak_v;
DROP MATERIALIZED VIEW player_level_win_streak;
DROP VIEW player_level_win_streak_v;
DROP MATERIALIZED VIEW player_best_of_win_streak;
DROP VIEW player_best_of_win_streak_v;
DROP MATERIALIZED VIEW player_surface_win_streak;
DROP VIEW player_surface_win_streak_v;
DROP MATERIALIZED VIEW player_indoor_win_streak;
DROP VIEW player_indoor_win_streak_v;
DROP MATERIALIZED VIEW player_vs_no1_win_streak;
DROP VIEW player_vs_no1_win_streak_v;
DROP MATERIALIZED VIEW player_vs_top5_win_streak;
DROP VIEW player_vs_top5_win_streak_v;
DROP MATERIALIZED VIEW player_vs_top10_win_streak;
DROP VIEW player_vs_top10_win_streak_v;
DROP MATERIALIZED VIEW player_tournament_win_streak;
DROP VIEW player_tournament_win_streak_v;
DROP MATERIALIZED VIEW player_tournament_level_win_streak;
DROP VIEW player_tournament_level_win_streak_v;

DROP VIEW player_big_wins_v;
DROP VIEW player_match_performance_v;
DROP VIEW player_match_stats_v;
DROP VIEW player_match_for_stats_v;
DROP VIEW match_for_stats_v;
DROP VIEW match_for_rivalry_v;

DROP MATERIALIZED VIEW player_titles;
DROP VIEW player_titles_v;
DROP MATERIALIZED VIEW player_tournament_event_result;
DROP VIEW player_tournament_event_result_v;

DROP VIEW in_progress_event_participation_v;
DROP MATERIALIZED VIEW event_participation;
DROP VIEW event_participation_v;
