REFRESH MATERIALIZED VIEW event_participation;
REFRESH MATERIALIZED VIEW player_tournament_event_result;
REFRESH MATERIALIZED VIEW player_titles;
REFRESH MATERIALIZED VIEW player_team_titles;

REFRESH MATERIALIZED VIEW player_current_rank;
REFRESH MATERIALIZED VIEW player_best_rank;
REFRESH MATERIALIZED VIEW player_best_rank_points;
REFRESH MATERIALIZED VIEW player_year_end_rank;
REFRESH MATERIALIZED VIEW player_current_elo_rank;
REFRESH MATERIALIZED VIEW player_best_elo_rank;
REFRESH MATERIALIZED VIEW player_best_elo_rating;
REFRESH MATERIALIZED VIEW player_season_best_elo_rating;
REFRESH MATERIALIZED VIEW player_year_end_elo_rank;
REFRESH MATERIALIZED VIEW player_season_weeks_at_no1;
REFRESH MATERIALIZED VIEW player_weeks_at_no1;
REFRESH MATERIALIZED VIEW player_season_weeks_at_elo_topn;
REFRESH MATERIALIZED VIEW player_weeks_at_elo_topn;
REFRESH MATERIALIZED VIEW player_season_weeks_at_surface_elo_topn;
REFRESH MATERIALIZED VIEW player_weeks_at_surface_elo_topn;

REFRESH MATERIALIZED VIEW player_season_performance;
REFRESH MATERIALIZED VIEW player_tournament_performance;
REFRESH MATERIALIZED VIEW player_performance;
REFRESH MATERIALIZED VIEW player_season_surface_stats;
REFRESH MATERIALIZED VIEW player_season_stats;
REFRESH MATERIALIZED VIEW player_surface_stats;
REFRESH MATERIALIZED VIEW player_stats;

REFRESH MATERIALIZED VIEW event_stats;
REFRESH MATERIALIZED VIEW player_h2h;
REFRESH MATERIALIZED VIEW title_difficulty;

REFRESH MATERIALIZED VIEW player_win_streak;
REFRESH MATERIALIZED VIEW player_level_win_streak;
REFRESH MATERIALIZED VIEW player_best_of_win_streak;
REFRESH MATERIALIZED VIEW player_surface_win_streak;
REFRESH MATERIALIZED VIEW player_indoor_win_streak;
REFRESH MATERIALIZED VIEW player_vs_no1_win_streak;
REFRESH MATERIALIZED VIEW player_vs_top5_win_streak;
REFRESH MATERIALIZED VIEW player_vs_top10_win_streak;
REFRESH MATERIALIZED VIEW player_tournament_win_streak;
REFRESH MATERIALIZED VIEW player_tournament_level_win_streak;

REFRESH MATERIALIZED VIEW player_season_goat_points;
REFRESH MATERIALIZED VIEW player_goat_points;
REFRESH MATERIALIZED VIEW player_surface_season_goat_points;
REFRESH MATERIALIZED VIEW player_surface_goat_points;
REFRESH MATERIALIZED VIEW player_tournament_goat_points;
