DROP FUNCTION load_player(INTEGER, TEXT, TEXT, DATE, TEXT, TEXT) CASCADE;
DROP FUNCTION load_ranking(DATE, INTEGER, INTEGER, INTEGER) CASCADE;
DROP FUNCTION load_ranking(DATE, TEXT, INTEGER, INTEGER) CASCADE;
DROP FUNCTION load_match(
	TEXT, SMALLINT, DATE, TEXT, TEXT, TEXT, TEXT, BOOLEAN, TEXT, SMALLINT, INTEGER, SMALLINT, TEXT, SMALLINT,
	INTEGER, SMALLINT, TEXT, INTEGER, INTEGER, REAL, TEXT, TEXT, SMALLINT, TEXT,
	INTEGER, SMALLINT, TEXT, INTEGER, INTEGER, REAL, TEXT, TEXT, SMALLINT, TEXT,
	TEXT, TEXT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT[], SMALLINT[], SMALLINT[], SMALLINT[], SMALLINT,
	SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT,
	SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT
) CASCADE;
