DROP FUNCTION extract_first_name(TEXT) CASCADE;
DROP FUNCTION extract_last_name(TEXT) CASCADE;
DROP FUNCTION find_player(TEXT, DATE) CASCADE;
DROP FUNCTION map_ext_player(INTEGER) CASCADE;
DROP FUNCTION map_ext_tournament(TEXT) CASCADE;
DROP FUNCTION merge_tournament(TEXT, TEXT, TEXT, TEXT, BOOLEAN) CASCADE;
DROP FUNCTION merge_tournament_event(TEXT, SMALLINT, DATE, TEXT, TEXT, TEXT, TEXT, BOOLEAN, TEXT, SMALLINT, INTEGER) CASCADE;
DROP PROCEDURE merge_player(INTEGER, TEXT, TEXT, SMALLINT, TEXT) CASCADE;
DROP PROCEDURE load_player(INTEGER, TEXT, TEXT, DATE, TEXT, TEXT) CASCADE;
DROP PROCEDURE load_ranking(DATE, INTEGER, INTEGER, INTEGER) CASCADE;
DROP PROCEDURE load_ranking(DATE, TEXT, INTEGER, INTEGER) CASCADE;
DROP PROCEDURE load_match(
	TEXT, SMALLINT, DATE, TEXT, TEXT, TEXT, TEXT, BOOLEAN, TEXT, SMALLINT, INTEGER, SMALLINT, DATE, TEXT, SMALLINT,
	INTEGER, SMALLINT, TEXT, INTEGER, INTEGER, REAL, TEXT, TEXT, SMALLINT, TEXT,
	INTEGER, SMALLINT, TEXT, INTEGER, INTEGER, REAL, TEXT, TEXT, SMALLINT, TEXT,
	TEXT, TEXT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT[], SMALLINT[], SMALLINT[], SMALLINT[], SMALLINT[], SMALLINT[], SMALLINT,
	SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT,
	SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT
) CASCADE;
DROP PROCEDURE load_match_stats(
    BIGINT, SMALLINT,
    SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT,
    SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT
) CASCADE;
DROP FUNCTION find_players(TEXT, DATE) CASCADE;
DROP PROCEDURE merge_match_prices(BIGINT, TEXT, REAL, REAL) CASCADE;
DROP PROCEDURE load_match_prices(SMALLINT, TEXT, TEXT, DATE, TEXT, TEXT, TEXT, TEXT,
	REAL, REAL, REAL, REAL, REAL, REAL, REAL, REAL) CASCADE;
DROP PROCEDURE load_in_progress_event(TEXT, DATE, TEXT, TEXT, TEXT, BOOLEAN, TEXT, SMALLINT);
DROP FUNCTION find_in_progress_event(TEXT);
DROP FUNCTION find_in_progress_match(INTEGER, SMALLINT);
DROP PROCEDURE load_in_progress_match(TEXT, SMALLINT, SMALLINT, SMALLINT, DATE, TEXT, BOOLEAN, TEXT, SMALLINT,
	TEXT, TEXT, SMALLINT, TEXT, TEXT, TEXT, SMALLINT, TEXT, SMALLINT, TEXT, TEXT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT[], SMALLINT[], SMALLINT[], SMALLINT[], SMALLINT,
	SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT,
	SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT, SMALLINT
);
DROP PROCEDURE load_player_in_progress_result(INTEGER, INTEGER, TEXT, TEXT, REAL, REAL, REAL);
DROP PROCEDURE create_player(TEXT, TEXT, DATE, TEXT);
DROP PROCEDURE fix_rank_points(DATE, DATE);
DROP PROCEDURE set_tournament_map_properties(TEXT, INTEGER, INTEGER, INTEGER[], JSON) CASCADE;
DROP PROCEDURE set_tournament_event_surface(INTEGER, TEXT, TEXT, BOOLEAN) CASCADE;
DROP PROCEDURE link_tournament(TEXT, TEXT) CASCADE;
DROP PROCEDURE link_tournament_events(TEXT, TEXT, int4range) CASCADE;
DROP PROCEDURE set_player_matches_country(TEXT, TEXT, DATE) CASCADE;
DROP PROCEDURE split_careers(TEXT, TEXT, DATE) CASCADE;
DROP PROCEDURE merge_careers(TEXT, TEXT) CASCADE;