REFRESH MATERIALIZED VIEW player_current_rank;
REFRESH MATERIALIZED VIEW player_best_rank;
REFRESH MATERIALIZED VIEW player_best_rank_points;
REFRESH MATERIALIZED VIEW tournament_event_player_result;
REFRESH MATERIALIZED VIEW player_goat_points;