REFRESH MATERIALIZED VIEW player_current_rank;
REFRESH MATERIALIZED VIEW player_best_rank;
REFRESH MATERIALIZED VIEW player_best_rank_points;
REFRESH MATERIALIZED VIEW player_tournament_event_result;
REFRESH MATERIALIZED VIEW player_goat_points;
REFRESH MATERIALIZED VIEW player_titles;
REFRESH MATERIALIZED VIEW CONCURRENTLY player_performance;
REFRESH MATERIALIZED VIEW player_stats;